### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by Guerillah** [PatrickBaus/Arduino-AD57X1#1]
Hey Patrick,

Thanks for the library. I am attempting to build it on an Arduino Uno and getting a good deal of warnings/errors which cause the build to fail. Do you have an example laying around anywhere? I'll attach the errors and .ino I have in subsequent posts...

**Comment by Guerillah** [comment]
Arduino IDE errors:











In file included from C:\Users\ddavis\Documents\Arduino\ad5791_dac_sketch\ad5791_dac_sketch.ino:1:0:

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:42:50: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t WRITE_REGISTERS = 0 << 23;

                                                  ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:43:49: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t READ_REGISTERS = 1 << 23;

                                                 ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:49:51: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t DAC_REGISTER = 0b001 << 20;

                                                   ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:52:55: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t CONTROL_REGISTER = 0b010 << 20;

                                                       ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:64:56: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t CLEARCODE_REGISTER = 0b011 <<20;

                                                        ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master/ad57X1.h:67:58: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t SW_CONTROL_REGISTER = 0b100 << 20;

                                                          ^

In file included from C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:15:0:

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:42:50: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t WRITE_REGISTERS = 0 << 23;

                                                  ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:43:49: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t READ_REGISTERS = 1 << 23;

                                                 ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:49:51: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t DAC_REGISTER = 0b001 << 20;

                                                   ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:52:55: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t CONTROL_REGISTER = 0b010 << 20;

                                                       ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:64:56: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t CLEARCODE_REGISTER = 0b011 <<20;

                                                        ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.h:67:58: warning: left shift count >= width of type [-Wshift-count-overflow]

     static const uint32_t SW_CONTROL_REGISTER = 0b100 << 20;

                                                          ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp: In constructor 'AD5781::AD5781(uint8_t, uint8_t)':

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:17:38: warning: integer overflow in expression [-Woverflow]

 #define AD5781_SPI_CLOCK_FREQ (1*1000*1000)   // 30 MHz SPI clock is the maximum specified

                                      ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:20:113: note: in expansion of macro 'AD5781_SPI_CLOCK_FREQ'

 AD5781::AD5781(uint8_t cs_pin, uint8_t ldac_pin) : cs_pin(cs_pin), ldac_pin(ldac_pin), spi_settings(SPISettings(AD5781_SPI_CLOCK_FREQ, MSBFIRST, SPI_MODE1)) {

                                                                                                                 ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp: In constructor 'AD5781::AD5781(uint8_t)':

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:17:38: warning: integer overflow in expression [-Woverflow]

 #define AD5781_SPI_CLOCK_FREQ (1*1000*1000)   // 30 MHz SPI clock is the maximum specified

                                      ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:23:89: note: in expansion of macro 'AD5781_SPI_CLOCK_FREQ'

 AD5781::AD5781(uint8_t cs_pin) : cs_pin(cs_pin), ldac_pin(-1), spi_settings(SPISettings(AD5781_SPI_CLOCK_FREQ, MSBFIRST, SPI_MODE1)) {

                                                                                         ^

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp: In member function 'void AD5781::writeSPI(uint32_t)':

C:\Users\ddavis\Documents\Arduino\libraries\Arduino-AD57X1-master\ad57X1.cpp:28:3: error: 'SPI1' was not declared in this scope

   SPI1.beginTransaction(this->spi_settings);

   ^

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by Guerillah** [comment]
Sketch... nothing much.

#include <ad57X1.h>
#include <SPI.h>
#include <Wire.h>

#define ldac 7
#define cs 6

AD5781 ad5781(cs, ldac);

void setup() {
ad5781.begin();
}

void loop() {
}

**Comment by PatrickBaus** [comment]
Hi Guerillah,

thank you very much for reporting these issues. Indeed the library did not compile on 8-bit microcontrollers like the Uno. The problem was, that the default datatype on these MCUs is 8 bit wide. I only used the library on 32 bit MCUs in the past, so that did not pop up.

I fixed that in dbe598b17678517faf41f3eaa220c7ab0cd0870a .

I also added some more changes to the constructor. It is now possible to choose the SPI frequency. I will add an example in the next commit.

**Comment by PatrickBaus** [comment]
Do check out the new example.

**Comment by Guerillah** [comment]
Thanks Patrick, i'll check it out tomorrow!

**Comment by Guerillah** [comment]
Patrick,

It now works with no issues on an Arduino Uno R3. Thanks again!
